version: "3.8"

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.nginx.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
      - php
      - assests

  php:
    build:
      context: .
      dockerfile: Dockerfile.php.prod

  assests:
    image: node:current-alpine
    volumes:
      - ./src/:/var/www/html
    working_dir: /var/www/html
    command: ["/bin/sh", "-c", "npm install && npm run production"]
