FROM composer:2.7.2


ARG COMPOSERUSER=laravel
ARG COMPOSERGROUP=laravel

RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s intl
RUN docker-php-ext-enable sodium bz2 zip

RUN adduser -g ${COMPOSERGROUP} -s /sh/bin -D ${COMPOSERUSER}

USER ${COMPOSERUSER}
# ENTRYPOINT [ "composer", "require" ]