FROM nginx:stable-alpine

ARG NGINXUSER=laravel
ARG NGINXGROUP=laravel

WORKDIR /var/www/html/public

ADD dev/default.conf /etc/nginx/conf.d/default.conf

# RUN sed -i "s/user www-data/user laravel/g" /etc/nginx/nginx.conf
RUN sed -i "s/user nginx/user laravel/g" /etc/nginx/nginx.conf

# create a system user w/o home (-D) called laravel with shell `/bin/sh` and add to group laravel
RUN adduser -g ${NGINXGROUP} -s /bin/sh -D ${NGINXUSER}